#
#policy_path: "{ROOT_DIR}/logs/rsl_rl/unitree_go2_flat/2025-01-20_09-29-18/exported/policy.pt"
policy_path: "{ROOT_DIR}/logs/rsl_rl/unitree_go2_flat/2025-01-20_15-07-06/exported/policy.pt"
xml_path: "{UNITREE_MUJOCO_DIR}/unitree_robots/go2/scene.xml"
task: "Isaac-Velocity-Flat-Unitree-Go2-v0"

# Total simulation time
simulation_duration: 60.0
# Simulation time step
simulation_dt: 0.002
# Controller update frequency (meets the requirement of simulation_dt * control_decimation=0.02; 50Hz)
control_decimation: 10

kps: [25., 25., 25., 25., 25., 25., 25., 25., 25., 25., 25., 25.]
kds: [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]

default_angles: [-0.1, 0.8, -1.5, 0.1, 0.8, -1.5, -0.1, 1.0, -1.5, 0.1, 1.0, -1.5]
#                FR_h  FR_t FR_c  FL_h FL_t FL_c  RR_h  RR_t RR_c  RL_h RL_t RL_c
isaac2mujoco: [1, 5, 9, 0, 4, 8, 3, 7, 11, 2, 6, 10]

ang_vel_scale: 1.0
dof_pos_scale: 1.0
dof_vel_scale: 1.0
action_scale: 0.25
cmd_scale: [1., 1., 1.]
num_actions: 12
num_obs: 48

cmd_init: [0.5, 0, 0]